#!/bin/bash

pushd ${OPENSHIFT_REPO_DIR} > /dev/null
echo "Migrating database"
echo "exec rake db:migrate RAILS_ENV=${RAILS_ENV:-production}"
bundle exec rake db:migrate RAILS_ENV="production"
popd > /dev/null
