# Postgres Database
development:
  adapter: postgresql
  database: smart_garden_client_dev
  pool: 10

test:
  adapter: postgresql
  database: smart_garden_client_test
  pool: 10

production:
  adapter: postgresql
  database: <%=ENV['OPENSHIFT_APP_NAME']%>
  username: <%=ENV['OPENSHIFT_POSTGRESQL_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_POSTGRESQL_DB_PASSWORD']%>
  host:   <%=ENV['OPENSHIFT_POSTGRESQL_DB_HOST']%>
  port:   <%=ENV['OPENSHIFT_POSTGRESQL_DB_PORT']%>
