# Postgres Database
development:
  adapter: postgresql
  database: smart_garden_client_dev
  pool: 10

test:
  adapter: postgresql
  database: smart_garden_client_test
  pool: 10

production:
  adapter: postgresql
  database: smart_garden_client_prod
  pool: 5
